"""
Person Detection — Report Generator
======================================
Generates JSON and Markdown session reports from detection statistics.
"""

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Dict, Optional

from ai.logger import setup_logger
from ai.utils import ensure_directory


class ReportGenerator:
    """Generates structured detection reports in JSON and Markdown."""

    def __init__(self, reports_dir: Path, logger: Optional[logging.Logger] = None):
        """
        Initialize the report generator.

        Parameters
        ----------
        reports_dir : Path
            Directory to save reports in.
        logger : logging.Logger, optional
            Logger instance.
        """
        self.reports_dir = ensure_directory(reports_dir)
        self.logger = logger or setup_logger("report_generator")

    def generate(self, stats: Dict) -> tuple:
        """
        Generate both JSON and Markdown reports.

        Parameters
        ----------
        stats : Dict
            Session statistics from VideoProcessor.

        Returns
        -------
        tuple[Path, Path]
            Paths to the JSON and Markdown report files.
        """
        self.logger.info("Generating detection reports...")

        json_path = self.generate_json(stats)
        md_path = self.generate_markdown(stats)

        self.logger.info(f"JSON report: {json_path}")
        self.logger.info(f"Markdown report: {md_path}")

        return json_path, md_path

    def generate_json(self, stats: Dict) -> Path:
        """
        Save session statistics as a JSON report.

        Parameters
        ----------
        stats : Dict
            Session statistics.

        Returns
        -------
        Path
            Path to the generated JSON file.
        """
        report_data = {
            "report_type": "person_detection",
            "module": "Module 3 — Phase 1",
            "generated_at": datetime.now().isoformat(),
            **stats,
        }

        json_path = self.reports_dir / "person_detection_report.json"
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(report_data, f, indent=2, ensure_ascii=False)

        return json_path

    def generate_markdown(self, stats: Dict) -> Path:
        """
        Save session statistics as a Markdown report.

        Parameters
        ----------
        stats : Dict
            Session statistics.

        Returns
        -------
        Path
            Path to the generated Markdown file.
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # Format duration
        duration = stats.get("video_duration_sec", 0)
        mins = int(duration // 60)
        secs = duration % 60
        duration_str = f"{mins}m {secs:.1f}s" if mins > 0 else f"{secs:.1f}s"

        md_content = f"""# Person Detection Report

> **Module 3 — Phase 1: Camera/Video Input + Person Detection**
>
> Generated: {timestamp}

---

## Video Information

| Property | Value |
|---|---|
| Filename | `{stats.get('video_filename', 'N/A')}` |
| Path | `{stats.get('video_path', 'N/A')}` |
| Resolution | {stats.get('video_resolution', 'N/A')} |
| FPS | {stats.get('video_fps', 'N/A')} |
| Duration | {duration_str} |
| Total Frames | {stats.get('total_frames_processed', 0):,} |

---

## Detection Results

| Metric | Value |
|---|---|
| Total Frames Processed | {stats.get('total_frames_processed', 0):,} |
| Frames Containing Persons | {stats.get('total_frames_with_persons', 0):,} |
| Total Person Detections | {stats.get('total_person_detections', 0):,} |
| Average Confidence | {stats.get('average_confidence', 0):.4f} |

---

## Performance

| Metric | Value |
|---|---|
| Average Inference Time | {stats.get('average_inference_time_ms', 0):.2f} ms |
| Total Pipeline Time | {stats.get('total_pipeline_time_sec', 0):.2f} s |
| Effective FPS | {stats.get('effective_fps', 0):.2f} |

---

## Configuration

| Setting | Value |
|---|---|
| Device | `{stats.get('device', 'N/A')}` |
| Model | `{stats.get('model', 'N/A')}` |
| Confidence Threshold | {stats.get('confidence_threshold', 'N/A')} |
| Image Size | {stats.get('image_size', 'N/A')} |
| Save Frames | {stats.get('save_frames', False)} |

---

## Output

| Output | Path |
|---|---|
| Annotated Video | `{stats.get('output_video', 'N/A')}` |

---

*Report generated by Indrani Consumer Attention Mapping System — AI Module*
"""

        md_path = self.reports_dir / "person_detection_report.md"
        with open(md_path, "w", encoding="utf-8") as f:
            f.write(md_content)

        return md_path
