"""
Attention Report — Markdown Writer
======================================
Generates the comprehensive Markdown attention report with all 15 sections.
Clearly distinguishes zone dwell time from estimated attention time.
"""

import logging
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from ai.attention_report.config import ReportConfig
from ai.logger import setup_logger
from ai.utils import ensure_directory


class MarkdownReportWriter:
    """Generates the Phase 6 Markdown report."""

    def __init__(self, config: ReportConfig, logger: Optional[logging.Logger] = None):
        self.config = config
        self.reports_dir = ensure_directory(config.reports_dir)
        self.logger = logger or setup_logger("markdown_writer")

    def write(self, report: Dict[str, Any]) -> Path:
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        lines: List[str] = []

        lines.append("# Consumer Attention Analysis Report")
        lines.append("")
        lines.append(f"> **Module 3 — Phase 6: Attention Reports**")
        lines.append(f">")
        lines.append(f"> Generated: {timestamp}")
        lines.append(f">")
        lines.append(f"> Report Version: {self.config.report_version}")
        lines.append("")
        lines.append("> **Note:** All attention values in this report are *estimated* based on")
        lines.append("> head orientation. They do NOT represent pixel-level eye gaze tracking.")
        lines.append("> Zone dwell time and estimated attention time are distinct metrics.")
        lines.append("")
        lines.append("---")
        lines.append("")

        self._section_executive_summary(lines, report)
        self._section_shopper_analytics(lines, report)
        self._section_zone_analytics(lines, report)
        self._section_dwell_time_analytics(lines, report)
        self._section_attention_analytics(lines, report)
        self._section_attention_targets(lines, report)
        self._section_attention_direction(lines, report)
        self._section_attention_confidence(lines, report)
        self._section_dwell_vs_attention(lines, report)
        self._section_repeated_attention(lines, report)
        self._section_top_zones(lines, report)
        self._section_top_targets(lines, report)
        self._section_time_based(lines, report)
        self._section_data_quality(lines, report)
        self._section_limitations(lines)

        lines.append("---")
        lines.append(f"*Report generated by Indrani Consumer Attention Mapping System — Module 3 Phase 6*")
        lines.append("")

        path = self.reports_dir / "attention_report.md"
        with open(path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))

        self.logger.info(f"Markdown report generated: {path}")
        return path

    # ── Section Writers ──────────────────────────────────────────

    def _section_executive_summary(self, lines: List[str], report: Dict) -> None:
        lines.append("## 1. Executive Summary")
        lines.append("")
        s = report.get("summary", {})
        lines.append("| Metric | Value |")
        lines.append("|---|---|")
        lines.append(f"| **Total Unique Shoppers** | **{s.get('total_unique_shoppers', 0)}** |")
        lines.append(f"| Total Sessions | {s.get('total_sessions', 0)} |")
        lines.append(f"| Completed Sessions | {s.get('completed_sessions', 0)} |")
        lines.append(f"| Track-Lost Sessions | {s.get('track_lost_sessions', 0)} |")
        lines.append(f"| Total Entries | {s.get('total_entries', 0)} |")
        lines.append(f"| Total Exits | {s.get('total_exits', 0)} |")
        lines.append(f"| Average Session Duration | {self._fmt(s.get('average_session_duration_sec'))}s |")
        lines.append(f"| Total Zone Visits | {s.get('total_zone_visits', 0)} |")
        lines.append(f"| Average Zone Dwell Time | {self._fmt(s.get('average_zone_dwell_time_sec'))}s |")
        lines.append(f"| Total Attention Events | {s.get('total_attention_events', 0)} |")
        lines.append(f"| Total Est. Attention Duration | {self._fmt(s.get('total_estimated_attention_duration_sec'))}s |")
        lines.append(f"| Average Est. Attention Duration | {self._fmt(s.get('average_estimated_attention_duration_sec'))}s |")
        lines.append(f"| Number of Attention Targets | {s.get('number_of_attention_targets', 0)} |")

        mv = s.get("most_visited_zone")
        lines.append(f"| Most Visited Zone | {mv['zone_name'] + ' (' + str(mv['total_visits']) + ' visits)' if mv else '—'} |")

        hd = s.get("zone_with_highest_average_dwell")
        lines.append(f"| Highest Avg Dwell Zone | {hd['zone_name'] + ' (' + self._fmt(hd.get('average_dwell_seconds')) + 's)' if hd else '—'} |")

        ma = s.get("most_attended_target")
        lines.append(f"| Most Attended Target | {ma['target_name'] + ' (' + self._fmt(ma.get('total_attention_sec')) + 's)' if ma else '—'} |")
        lines.append("")
        lines.append("---")
        lines.append("")

    def _section_shopper_analytics(self, lines: List[str], report: Dict) -> None:
        lines.append("## 2. Shopper Analytics")
        lines.append("")
        shoppers = report.get("shoppers", [])
        if not shoppers:
            lines.append("*No shopper data available.*")
            lines.append("")
            return

        lines.append("| ID | Session | Status | Duration | Zones | Zone Visits | Dwell (s) | Attn Events | Est. Attn (s) | Most Attended |")
        lines.append("|---|---|---|---|---|---|---|---|---|---|")
        for sh in shoppers[:50]:
            zones = ", ".join(sh.get("zones_visited", [])) or "—"
            lines.append(
                f"| {sh.get('tracking_id')} "
                f"| {sh.get('session_id', '—')} "
                f"| {sh.get('session_status', '—')} "
                f"| {self._fmt(sh.get('session_duration_sec'))}s "
                f"| {zones} "
                f"| {sh.get('number_of_zone_visits', 0)} "
                f"| {self._fmt(sh.get('total_zone_dwell_time_sec'))} "
                f"| {sh.get('attention_event_count', 0)} "
                f"| {self._fmt(sh.get('total_estimated_attention_duration_sec'))} "
                f"| {sh.get('most_attended_target', '—')} |"
            )
        if len(shoppers) > 50:
            lines.append(f"| ... | *{len(shoppers) - 50} more shoppers* | | | | | | | | |")
        lines.append("")
        lines.append("---")
        lines.append("")

    def _section_zone_analytics(self, lines: List[str], report: Dict) -> None:
        lines.append("## 3. Zone Analytics")
        lines.append("")
        lines.append("> **Zone Dwell Time** = time a shopper was observed inside a zone.")
        lines.append("> **Estimated Attention Time** = time estimated head/gaze direction was directed toward a target.")
        lines.append("")
        zones = report.get("zones", [])
        if not zones:
            lines.append("*No zone data available.*")
            lines.append("")
            return

        lines.append("| Zone | Visitors | Visits | Total Dwell (s) | Avg Dwell (s) | Median Dwell (s) | Max Dwell (s) | Attn Events | Est. Attn (s) |")
        lines.append("|---|---|---|---|---|---|---|---|---|")
        for z in zones:
            lines.append(
                f"| {z.get('zone_name')} "
                f"| {z.get('unique_visitors', 0)} "
                f"| {z.get('total_visits', 0)} "
                f"| {self._fmt(z.get('total_dwell_time_sec'))} "
                f"| {self._fmt(z.get('average_dwell_time_sec'))} "
                f"| {self._fmt(z.get('median_dwell_time_sec'))} "
                f"| {self._fmt(z.get('maximum_dwell_time_sec'))} "
                f"| {z.get('attention_event_count', 0)} "
                f"| {self._fmt(z.get('total_estimated_attention_duration_sec'))} |"
            )
        lines.append("")
        lines.append("---")
        lines.append("")

    def _section_dwell_time_analytics(self, lines: List[str], report: Dict) -> None:
        lines.append("## 4. Dwell-Time Analytics")
        lines.append("")
        dva = report.get("dwell_vs_attention", {}).get("zones", [])
        if dva:
            lines.append("| Zone | Total Dwell (s) | Avg Dwell (s) |")
            lines.append("|---|---|---|")
            for z in dva:
                lines.append(f"| {z.get('zone_name')} | {self._fmt(z.get('total_dwell_time_sec'))} | {self._fmt(z.get('average_dwell_time_sec'))} |")
        else:
            lines.append("*No dwell-time data available.*")
        lines.append("")
        lines.append("---")
        lines.append("")

    def _section_attention_analytics(self, lines: List[str], report: Dict) -> None:
        lines.append("## 5. Attention Analytics")
        lines.append("")
        s = report.get("summary", {})
        lines.append(f"- **Total Attention Events:** {s.get('total_attention_events', 0)}")
        lines.append(f"- **Total Estimated Attention Duration:** {self._fmt(s.get('total_estimated_attention_duration_sec'))}s")
        lines.append(f"- **Average Estimated Attention Duration:** {self._fmt(s.get('average_estimated_attention_duration_sec'))}s")
        lines.append(f"- **Detection Method:** Head Orientation (MediaPipe + solvePnP)")
        lines.append("")
        lines.append("---")
        lines.append("")

    def _section_attention_targets(self, lines: List[str], report: Dict) -> None:
        lines.append("## 6. Attention Target Analytics")
        lines.append("")
        targets = report.get("targets", [])
        if not targets:
            lines.append("*No attention target data available.*")
            lines.append("")
            return

        lines.append("| Target | Type | Shoppers | Events | Total Est. Attn (s) | Avg (s) | Max (s) | Repeats |")
        lines.append("|---|---|---|---|---|---|---|---|")
        for t in targets:
            lines.append(
                f"| {t.get('target_name')} "
                f"| {t.get('target_type', 'unknown')} "
                f"| {t.get('unique_shoppers', 0)} "
                f"| {t.get('attention_event_count', 0)} "
                f"| {self._fmt(t.get('total_estimated_attention_duration_sec'))} "
                f"| {self._fmt(t.get('average_attention_duration_sec'))} "
                f"| {self._fmt(t.get('maximum_attention_duration_sec'))} "
                f"| {t.get('repeat_attention_count', 0)} |"
            )
        lines.append("")
        lines.append("---")
        lines.append("")

    def _section_attention_direction(self, lines: List[str], report: Dict) -> None:
        lines.append("## 7. Attention Direction")
        lines.append("")
        lines.append("> **ESTIMATED ATTENTION DIRECTION** — This does NOT represent exact eye tracking")
        lines.append("> unless the source data explicitly supports it.")
        lines.append("")
        ad = report.get("attention_direction", {})
        directions = ad.get("directions", {})
        if not directions:
            lines.append("*No attention direction data available.*")
            lines.append("")
            return
        lines.append("| Direction | Observations | Percentage | Stable Events |")
        lines.append("|---|---|---|---|")
        for d_name, d_data in directions.items():
            lines.append(
                f"| {d_name} "
                f"| {d_data.get('observation_count', 0)} "
                f"| {self._fmt(d_data.get('percentage'))}% "
                f"| {d_data.get('stable_attention_event_count', 0)} |"
            )
        lines.append("")
        lines.append("---")
        lines.append("")

    def _section_attention_confidence(self, lines: List[str], report: Dict) -> None:
        lines.append("## 8. Attention Confidence")
        lines.append("")
        c = report.get("confidence", {})
        lines.append("| Metric | Value |")
        lines.append("|---|---|")
        lines.append(f"| Average Confidence | {self._fmt(c.get('average_confidence'), 4)} |")
        lines.append(f"| Minimum Confidence | {self._fmt(c.get('minimum_confidence'), 4)} |")
        lines.append(f"| Maximum Confidence | {self._fmt(c.get('maximum_confidence'), 4)} |")
        lines.append(f"| High-Confidence Observations | {c.get('high_confidence_observations', 0)} ({self._fmt(c.get('high_confidence_percentage'))}%) |")
        lines.append(f"| Low-Confidence Observations | {c.get('low_confidence_observations', 0)} ({self._fmt(c.get('low_confidence_percentage'))}%) |")
        lines.append(f"| Unknown Observations | {c.get('unknown_observations', 0)} ({self._fmt(c.get('unknown_percentage'))}%) |")
        lines.append("")
        lines.append("---")
        lines.append("")

    def _section_dwell_vs_attention(self, lines: List[str], report: Dict) -> None:
        lines.append("## 9. Dwell vs Estimated Attention")
        lines.append("")
        lines.append("> **IMPORTANT:** The attention-to-dwell ratio is purely descriptive.")
        lines.append("> It does NOT indicate purchase intent, customer interest, conversion probability, or product preference.")
        lines.append("")
        dva = report.get("dwell_vs_attention", {}).get("zones", [])
        if not dva:
            lines.append("*Insufficient data for dwell vs attention comparison.*")
            lines.append("")
            return
        lines.append("| Zone | Avg Dwell (s) | Avg Est. Attn (s) | Total Dwell (s) | Total Est. Attn (s) | Ratio |")
        lines.append("|---|---|---|---|---|---|")
        for z in dva:
            ratio = z.get("attention_to_dwell_ratio")
            ratio_str = self._fmt(ratio, 4) if ratio is not None else "N/A"
            lines.append(
                f"| {z.get('zone_name')} "
                f"| {self._fmt(z.get('average_dwell_time_sec'))} "
                f"| {self._fmt(z.get('average_estimated_attention_time_sec'))} "
                f"| {self._fmt(z.get('total_dwell_time_sec'))} "
                f"| {self._fmt(z.get('total_estimated_attention_time_sec'))} "
                f"| {ratio_str} |"
            )
        lines.append("")
        lines.append("---")
        lines.append("")

    def _section_repeated_attention(self, lines: List[str], report: Dict) -> None:
        lines.append("## 10. Repeated Attention")
        lines.append("")
        ra = report.get("repeated_attention", {})
        lines.append(f"- **Total Repeat Attention Count:** {ra.get('total_repeat_attention_count', 0)}")
        lines.append(f"- **Unique Shoppers with Repeated Attention:** {ra.get('unique_shoppers_with_repeated_attention', 0)}")
        lines.append(f"- **Most Repeatedly Attended Target:** {ra.get('most_repeatedly_attended_target', '—')}")
        lines.append("")
        repeated = ra.get("repeated_events", [])
        if repeated:
            for r in repeated[:20]:
                lines.append(f"### Shopper {r.get('tracking_id')}: {r.get('target_name')}")
                lines.append("")
                for ev in r.get("events", []):
                    dur = self._fmt(ev.get("duration_seconds"))
                    lines.append(f"- Event {ev.get('event_number')} → {dur}s")
                lines.append("")
        else:
            lines.append("*No repeated attention events detected.*")
            lines.append("")
        lines.append("---")
        lines.append("")

    def _section_top_zones(self, lines: List[str], report: Dict) -> None:
        lines.append("## 11. Top Zones")
        lines.append("")
        rankings = report.get("rankings", {}).get("top_zones", {})
        for ranking_name, items in rankings.items():
            label = ranking_name.replace("by_", "By ").replace("_", " ").title()
            lines.append(f"### {label}")
            lines.append("")
            if items:
                lines.append("| Rank | Zone | Value |")
                lines.append("|---|---|---|")
                key = ranking_name.replace("by_", "")
                for i, z in enumerate(items[:5], 1):
                    val = z.get(key, z.get(f"total_{key}", z.get(f"{key}_sec", "—")))
                    lines.append(f"| {i} | {z.get('zone_name', z.get('zone_id'))} | {val} |")
            else:
                lines.append("*No data.*")
            lines.append("")
        lines.append("---")
        lines.append("")

    def _section_top_targets(self, lines: List[str], report: Dict) -> None:
        lines.append("## 12. Top Attention Targets")
        lines.append("")
        rankings = report.get("rankings", {}).get("top_targets", {})
        for ranking_name, items in rankings.items():
            label = ranking_name.replace("by_", "By ").replace("_", " ").title()
            lines.append(f"### {label}")
            lines.append("")
            if items:
                lines.append("| Rank | Target | Value |")
                lines.append("|---|---|---|")
                key = ranking_name.replace("by_", "")
                for i, t in enumerate(items[:5], 1):
                    val = t.get(key, t.get(f"total_{key}", t.get(f"{key}_sec", "—")))
                    lines.append(f"| {i} | {t.get('target_name', t.get('target_id'))} | {val} |")
            else:
                lines.append("*No data.*")
            lines.append("")
        lines.append("---")
        lines.append("")

    def _section_time_based(self, lines: List[str], report: Dict) -> None:
        lines.append("## 13. Time-Based Analytics")
        lines.append("")
        ts = report.get("time_series", {})
        traffic = ts.get("shopper_traffic_over_time", [])
        if traffic:
            lines.append("### Shopper Traffic Over Time")
            lines.append("")
            lines.append("| Period | Active Shoppers |")
            lines.append("|---|---|")
            for p in traffic:
                lines.append(f"| {p.get('period', '—')} | {p.get('active_shoppers', 0)} |")
            lines.append("")
        else:
            lines.append("*No time-series data available.*")
            lines.append("")
        lines.append("> Note: All timestamps are video-relative. Do not interpret as real-world dates or business hours.")
        lines.append("")
        lines.append("---")
        lines.append("")

    def _section_data_quality(self, lines: List[str], report: Dict) -> None:
        lines.append("## 14. Data Quality")
        lines.append("")
        dq = report.get("data_quality", {})
        lines.append("| Metric | Value |")
        lines.append("|---|---|")
        lines.append(f"| Total Sessions | {dq.get('total_sessions', 0)} |")
        lines.append(f"| Completed Sessions | {dq.get('completed_sessions', 0)} |")
        lines.append(f"| Track-Lost Sessions | {dq.get('track_lost_sessions', 0)} ({self._fmt(dq.get('track_lost_percentage'))}%) |")
        lines.append(f"| Sessions Without Zone Assignment | {dq.get('sessions_without_zone_assignment', 0)} ({self._fmt(dq.get('missing_zone_percentage'))}%) |")
        lines.append(f"| Sessions Missing Entry Time | {dq.get('sessions_missing_entry_time', 0)} |")
        lines.append(f"| Sessions Missing Exit Time | {dq.get('sessions_missing_exit_time', 0)} |")
        lines.append(f"| Total Attention Observations | {dq.get('total_attention_observations', 0)} |")
        lines.append(f"| Unknown Attention Observations | {dq.get('unknown_attention_observations', 0)} ({self._fmt(dq.get('unknown_attention_percentage'))}%) |")
        lines.append(f"| Incomplete Attention Events | {dq.get('incomplete_attention_events', 0)} |")
        lines.append(f"| Missing Timestamps | {dq.get('missing_timestamps', 0)} |")
        lines.append("")
        lines.append("---")
        lines.append("")

    def _section_limitations(self, lines: List[str]) -> None:
        lines.append("## 15. Limitations")
        lines.append("")
        lines.append("The following limitations apply to this report:")
        lines.append("")
        lines.append("1. **Attention is estimated.** Values are based on head orientation, not direct eye gaze measurement.")
        lines.append("2. **Head pose as proxy.** Head pose is used as a proxy for gaze direction, which introduces uncertainty.")
        lines.append("3. **Camera resolution.** Camera resolution and viewing angle affect attention estimation accuracy.")
        lines.append("4. **Occlusion.** Occlusion of faces affects head-pose estimation reliability.")
        lines.append("5. **Track loss.** Track loss affects session duration and dwell-time calculations.")
        lines.append("6. **Product-level attention.** Product-level attention is only reported when explicitly supported by the source data.")
        lines.append("7. **Attention ≠ Purchase.** Attention does not imply purchase.")
        lines.append("8. **Attention ≠ Intent.** Attention does not imply purchase intent.")
        lines.append("9. **Dwell ≠ Attention.** Dwell time does not automatically indicate attention.")
        lines.append("10. **Estimated ≠ Exact.** Estimated attention is not necessarily exact eye gaze.")
        lines.append("")

    # ── Helpers ───────────────────────────────────────────────────

    @staticmethod
    def _fmt(value: Any, decimals: int = 2) -> str:
        if value is None:
            return "N/A"
        try:
            return f"{float(value):.{decimals}f}"
        except (ValueError, TypeError):
            return str(value)
